---
title: Niet-overeenkomende tags of brackets (haakjes)
hero_image: images/banner.png
description: Niet-overeenkomende tags of brackets (haakjes).
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Niet-overeenkomende tags of brackets (haakjes)
